[project]
name = "pdf-analysis"
version = "0.1.0"
description = ""
authors = [
    { name = "blee@filynai", email = "blee@filynai.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pdfplumber (>=0.11.7,<0.12.0)",
    "pdfminer.six (>=20221105,<20231200)",
    "pandas (>=2.3.3,<3.0.0)",
    "numpy (>=2.3.3,<3.0.0)",
    "pydantic (>=2.12.0,<3.0.0)",
    "pytesseract (>=0.3.13,<0.4.0)",
    "pdf2image (>=1.17.0,<2.0.0)",
    "camelot-py (>=1.0.9,<2.0.0)",
    "tabula-py (>=2.10.0,<3.0.0)",
    "reportlab (>=4.2.2,<5.0.0)"
]

[tool.poetry]
packages = [{ include = "pdf_analysis", from = "src" }]


[tool.poetry.group.dev.dependencies]
mypy = "^1.18.2"
pandas-stubs = "^2.3.2.250926"
types-requests = "^2.32.4.20250913"
types-pyyaml = "^6.0.12.20250915"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
ocr = ["pytesseract", "pdf2image"]
camelot = ["camelot-py"]
tabula = ["tabula-py"]


[tool.mypy]
python_version = "3.11"
pretty = true
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_incomplete_defs = true
no_implicit_optional = true
strict_optional = true
# If you use many third-party libs without type hints:
ignore_missing_imports = true
